model:
  text_encoder:
    vocab_size: 256 # ASCII character set
    embedding_dim: 512
    hidden_dim: 512
    num_layers: 3
    dropout: 0.1
  speaker_encoder:
    embedding_dim: 256
  emotion_encoder:
    embedding_dim: 128
  decoder:
    hidden_dim: 512
    num_layers: 4
    dropout: 0.1
